name: Python CI

on: 
  push:
    brnches: [main]
  pull_request:
    brnches: [main]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: checkaout del codigo
        uses: actions/checkaout@v3

      - name: checkaout del codigo
        uses: actions/checkaout@v3
        whit:
          python-version: '3.10'
      - name: instalar dependencias 
        run: |
            python -m pin install --upgrade pip
            pip install -r requirements.txt

      - name: Ejecutar pruebas 
        run: | 
            pyrest